/*
This program generates a data plot of the pink noise that is generated by the 
pcm_min.c file that can be found in the alsa lib test folder
*/
#include <stdlib.h>
#include "../include/asoundlib.h"
static char *device = "default";			/* playback device */
snd_output_t *output = NULL;
unsigned char buffer[4*1024];				/* an empty buffer of size 16384 bits */

int main(void)
{
        int err, i;
        snd_pcm_t *handle;
        snd_pcm_sframes_t frames;
		
		FILE *gnuplot = popen("gnuplot -persist","w");
		FILE * temp = fopen("data.dat", "w");
		fprintf(gnuplot, "set grid ytics lt 0 lw 1 lc rgb '#bbbbbb'\n");
		fprintf(gnuplot, "set grid xtics lt 0 lw 1 lc rgb '#bbbbbb'\n");
		//fprintf(gnuplot, "set xrange [0.000:20.000]\n");
		//fprintf(gnuplot, "set yrange [0.000:20.000]\n");
		fprintf(gnuplot, "set terminal png\n");
		fprintf(gnuplot, "set output 'pcm_min_data_plot.png'\n");
		//fprintf(gnuplot, "set title 'pcm_min_data_plot'\n");
		fprintf(gnuplot, "set xlabel 'Samples'\n");
		fprintf(gnuplot, "set ylabel 'Amplitude (raw values)'\n");		
		fprintf(gnuplot, "set style data lines\n");
		printf("coor = x | y\n");
		//for (i = 0; i < sizeof(buffer); i++){
		for (i = 0; i < 100; i++){
                buffer[i] = random() & 0xff;	
				printf("data = %d | %d\n",i, buffer[i]);
				fprintf(temp, "%d %d \n",i, buffer[i]);
		}	
		
		fprintf(gnuplot, "plot 'data.dat' linecolor rgb \"blue\"\n");
		fflush(gnuplot);	
		

/*
        if ((err = snd_pcm_open(&handle, device, SND_PCM_STREAM_PLAYBACK, 0)) < 0) {
                printf("Playback open error: %s\n", snd_strerror(err));
                exit(EXIT_FAILURE);
        }
        if ((err = snd_pcm_set_params(handle,
                                      SND_PCM_FORMAT_U8,
                                      SND_PCM_ACCESS_RW_INTERLEAVED,
                                      1,
                                      48000,
                                      1,
                                      500000)) < 0) {   // 0.5sec 
                printf("Playback open error: %s\n", snd_strerror(err));
                exit(EXIT_FAILURE);
        }
        for (i = 0; i < 16; i++) {
                frames = snd_pcm_writei(handle, buffer, sizeof(buffer));
                if (frames < 0)
                        frames = snd_pcm_recover(handle, frames, 0);
                if (frames < 0) {
                        printf("snd_pcm_writei failed: %s\n", snd_strerror(frames));
                        break;
                }
                if (frames > 0 && frames < (long)sizeof(buffer))
                        printf("Short write (expected %li, wrote %li)\n", (long)sizeof(buffer), frames);
        }
        snd_pcm_close(handle);



*/		
	return 0;
}